version: 2

# Set the OS, Python version and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# Python dependencies required for building docs
python:
  install:
    - method: pip
      path: .
      extras: "docs"
