[build-system]
requires = ["setuptools>=80.9.0", "wheel>=0.45.1"]
build-backend = "setuptools.build_meta"

[project]
name = "PyRth"
version = "1.3.0"
description = "A tool for thermal transient analysis"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICENSE.txt"]
authors = [
    { name = "Nils J. Ziegeler", email = "ziegeler.nilsjonas@fh-swf.de" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

dependencies = [
    "numpy>=2.2.0,<3.0.0",
    "scipy>=1.16.0,<2.0.0",
    "matplotlib>=3.10.0,<4.0.0",
    "numba>=0.63.0,<1.0.0",
    "gmpy2>=2.2.2,<3.0.0",
    "scikit-learn>=1.8.0,<2.0.0"
]

[project.optional-dependencies]
docs = [
    "sphinx>=8.2.0,<9.0.0",
    "sphinx-rtd-theme>=3.0.2,<4.0.0",
    "sphinx-proof>=0.3.0,<1.0.0",
    "myst-parser>=4.0.1,<5.0.0",
]
dev = [
    "pytest>=9.0.0,<10.0.0",
]


[project.urls]
Homepage = "https://github.com/nizie002/PyRth"

[tool.setuptools]
packages = ["PyRth", "PyRth.utils", "PyRth.exporter"]
